/*
This is the code to input a list and find the sum of numbers present in the list.
Example:-
[1,2]
Answer would display 3 
Ofcourse this is not how you add two different arrays but this is a nice introudction to work with list's using Python C API 
This code is generated by chatGPT 
*/

#define PY_SSIZE_T_CLEAN
#include <Python.h>

// Function to sum elements in a Python list
static PyObject* sum_array(PyObject* self, PyObject* args) {
    PyObject* listObj;  // Input Python list
    Py_ssize_t listSize;
    double sum = 0.0;

    // Parse the Python argument (expecting a list)
    if (!PyArg_ParseTuple(args, "O!"/*Symbol for expecting a list*/, &PyList_Type, &listObj)) {
        return NULL;  // Return NULL if parsing fails
    }

    listSize = PyList_Size(listObj);  // Get size of list

    // Iterate over the list
    for (Py_ssize_t i = 0; i < listSize; i++) {
        PyObject* item = PyList_GetItem(listObj, i);  // Get item
        if (!PyFloat_Check(item) && !PyLong_Check(item)) {  // Ensure it's a number
            PyErr_SetString(PyExc_TypeError, "List must contain only numbers");
            return NULL;
        }
        sum += PyFloat_AsDouble(item);  // Convert to C double and add
    }

    return PyFloat_FromDouble(sum);  // Return result as a Python float
}

// Define module methods
static PyMethodDef MyMethods[] = {
    {"sum_array", sum_array, METH_VARARGS, "Sum elements of a Python list"},
    {NULL, NULL, 0, NULL}  // Sentinel
};

// Define module
static struct PyModuleDef arraymodule = {
    PyModuleDef_HEAD_INIT,
    "array_module",
    "A module for handling arrays",
    -1,
    MyMethods
};

// Module initialization
PyMODINIT_FUNC PyInit_array_module(void) {
    return PyModule_Create(&arraymodule);
}
